### ISSUE TITLE
Slight issue trying to use project as-is

### ISSUE THREAD

**Issue by kristianmandrup** [benawad/aws-appsync-example#1]
I tried to clone the project, then run `amplify configure` and `yarn start`, however it complained.

```bash
./src/index.tsx
Module not found: Can't resolve './aws-exports' in '/Users/kristianmandrup/repos/appsync/aws-appsync-example/src'
```
I thought I should perhaps run `amplify init` to have it initialized with local configuration, but it fails...

```bash
$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Choose your default editor: Visual Studio Code
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using react
? Source Directory Path:  src
? Distribution Directory Path: build
? Build Command:  npm run-script build
? Start Command: npm run-script start
Using default provider awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use default
⠴ Initializing project in the cloud...An error occurred when creating the CloudFormation stack
✖ Root stack creation failed
init failed
{ OptInRequired: The AWS Access Key Id needs a subscription for the service
```

Hmm `AWS Access Key Id needs a subscription for the service`, I wonder if this is a missing setting in my AWS console during configuration?

```bash
$ amplify push
/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/gluegun/build/index.js:13
    throw up;
    ^

Error: You are not working inside a valid amplify project.
Use 'amplify init' in the root of your app directory to initialize your project with Amplify
```

After looking close at the video tutorial, the file `aws-exports` seems to appear after `amplify push` is completed. I'll try to create a new project from scratch instead.

Was just curious if this repo could be used as is, with a fresh `amplify configure` but couldn't make that work so far. Generators ;)

Cheers!

**Comment by kristianmandrup** [comment]
Hmm, seems to be a common issue: https://forums.aws.amazon.com/message.jspa?messageID=247187

This error message indicates that you have not signed up for Amazon Simple Email Service. Even if you currently have an AWS account - with an Access Key Id and a Secret Key - you still must explicitly sign up for Amazon SES.

Please double-check that you've signed up. Here's one way to tell:
Go to http://aws.amazon.com. Click the Account tab, and then Usage Reports.
Sign in with your Amazon user ID and password.
On the Usage Reports page, look for a drop-down list of services that you have subscribed to. Verify that Amazon SES is in that list.

If you don't see Amazon SES there, please go to http://aws.amazon.com/ses and click the button marked "Sign up for Amazon SES".

**Comment by kristianmandrup** [comment]
https://us-west-2.console.aws.amazon.com/console/signup?region=us-west-2

Your service sign-up is almost complete!
Thanks for signing up with Amazon Web Services. Your services may take up to 24 hours to fully activate. If you’re unable to access AWS services after that time, here are a few things you can do to expedite the process:

Make sure you provided all necessary information during signup. Complete your AWS registration.
Check your email to see if you have received any requests for additional information. If you have, please respond to those emails with the information requested.
Verify your credit card information is correct. Also, check your credit card activity to see if there’s a $1 authorization (this is not a charge). You may need to contact your card issuer to approve the authorization.

Also, when I created the app I chose eu-west-1, not sure if that could be an issue as well. I can imagine others following this tutorial might encounter similar issues, so there you have it

**Comment by benawad** [comment]
I guess you have to wait 24 hours before using it?

**Comment by kristianmandrup** [comment]
Yeah, it's all good. Just wanted to notify you so you can help anyone else running into it.
Thanks for the great tutorial and article :)

**Comment by Joe-Wilson-Barantum** [comment]
Your service sign-up is almost complete!
Thanks for signing up with Amazon Web Services. Your services may take up to 24 hours to fully activate. If you’re unable to access AWS services after that time, here are a few things you can do to expedite the process

have I should to take long time around 24 hours for the message above?
